-- ====================================================================
-- Flyway Migration: V26__sub_organizations_and_vice_managers.sql
-- Description: Sub-organizations, geo-coordinates, per-branch policies,
--              and Vice Manager role support.
-- ====================================================================

-- 1. Create sub_organizations table
CREATE TABLE IF NOT EXISTS sub_organizations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    slug                    VARCHAR(255) NOT NULL,
    is_default              BOOLEAN NOT NULL DEFAULT false,
    
    -- Geofence & Map Coordinates (WGS-84)
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    geo_radius_m            INTEGER DEFAULT 200,
    address_label           VARCHAR(500),
    
    -- Sub-org specific attendance policy overrides (NULL = inherit global default)
    entry_time              TIME,
    exit_time               TIME,
    lunch_start_time        TIME,
    lunch_end_time          TIME,
    grace_minutes           INTEGER,
    max_lunch_break_minutes INTEGER,
    
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT fk_sub_organizations_org 
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT uk_sub_org_org_slug 
        UNIQUE (organization_id, slug),
    CONSTRAINT uk_sub_org_org_name 
        UNIQUE (organization_id, name)
);

-- Partial index: only one default sub-org per organization
CREATE UNIQUE INDEX IF NOT EXISTS idx_sub_org_one_default 
    ON sub_organizations (organization_id) 
    WHERE is_default = true;

CREATE INDEX IF NOT EXISTS idx_sub_org_org 
    ON sub_organizations (organization_id);

-- 2. Populate default sub-org for all existing organizations
INSERT INTO sub_organizations (organization_id, name, slug, is_default, created_at, updated_at)
SELECT o.id, o.name || ' Main', 'main', true, now(), now()
FROM organizations o
WHERE NOT EXISTS (
    SELECT 1 FROM sub_organizations so 
    WHERE so.organization_id = o.id AND so.is_default = true
);

-- 3. Add sub_organization_id to employees
ALTER TABLE employees 
    ADD COLUMN IF NOT EXISTS sub_organization_id BIGINT;

-- Backfill existing employees to their organization's default sub-org
UPDATE employees e
SET sub_organization_id = (
    SELECT so.id 
    FROM sub_organizations so 
    WHERE so.organization_id = e.organization_id AND so.is_default = true
)
WHERE e.sub_organization_id IS NULL;

-- Make sub_organization_id NOT NULL and add foreign key
ALTER TABLE employees 
    ALTER COLUMN sub_organization_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_employees_sub_organization'
    ) THEN
        ALTER TABLE employees 
            ADD CONSTRAINT fk_employees_sub_organization 
            FOREIGN KEY (sub_organization_id) REFERENCES sub_organizations(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_employees_sub_organization 
    ON employees (sub_organization_id);

-- 4. Update managers table to support Vice Managers
ALTER TABLE managers 
    ADD COLUMN IF NOT EXISTS role VARCHAR(30) NOT NULL DEFAULT 'MANAGER';

ALTER TABLE managers 
    ADD COLUMN IF NOT EXISTS sub_organization_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_managers_sub_organization'
    ) THEN
        ALTER TABLE managers 
            ADD CONSTRAINT fk_managers_sub_organization 
            FOREIGN KEY (sub_organization_id) REFERENCES sub_organizations(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_managers_sub_organization 
    ON managers (sub_organization_id);

-- 5. Add coordinates and geofence tracking to employee_attendance
ALTER TABLE employee_attendance 
    ADD COLUMN IF NOT EXISTS clock_in_lat DOUBLE PRECISION;

ALTER TABLE employee_attendance 
    ADD COLUMN IF NOT EXISTS clock_in_lng DOUBLE PRECISION;

ALTER TABLE employee_attendance 
    ADD COLUMN IF NOT EXISTS geo_status VARCHAR(30);

ALTER TABLE employee_attendance 
    ADD COLUMN IF NOT EXISTS clock_in_distance_m DOUBLE PRECISION;

-- 6. Add optional sub-organization scoping to content entities
ALTER TABLE blogs 
    ADD COLUMN IF NOT EXISTS sub_organization_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_blogs_sub_organization'
    ) THEN
        ALTER TABLE blogs 
            ADD CONSTRAINT fk_blogs_sub_organization 
            FOREIGN KEY (sub_organization_id) REFERENCES sub_organizations(id) ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE events 
    ADD COLUMN IF NOT EXISTS sub_organization_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_events_sub_organization'
    ) THEN
        ALTER TABLE events 
            ADD CONSTRAINT fk_events_sub_organization 
            FOREIGN KEY (sub_organization_id) REFERENCES sub_organizations(id) ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE jobs 
    ADD COLUMN IF NOT EXISTS sub_organization_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_jobs_sub_organization'
    ) THEN
        ALTER TABLE jobs 
            ADD CONSTRAINT fk_jobs_sub_organization 
            FOREIGN KEY (sub_organization_id) REFERENCES sub_organizations(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_blogs_sub_org ON blogs (sub_organization_id);
CREATE INDEX IF NOT EXISTS idx_events_sub_org ON events (sub_organization_id);
CREATE INDEX IF NOT EXISTS idx_jobs_sub_org ON jobs (sub_organization_id);
